#!/bin/bash
toj="temp-one-jar"

make package2

# 1st time: or to reffresh remove comment with 2 #
#

# Create the One-JAR directory structure
mkdir -p $toj/main $toj/lib
# Unzip the One-JAR boot jar into the $toj directory
unzip -oq ./lib/one-jar-boot-0.97.jar -d $toj/
rm -rf $toj/src
# Move the Scala CLI-generated assembly jar to the main directory of One-JAR structure
cp CDA.jar $toj/main/main.jar
# Copy all library jars to the lib directory
cp lib/*.jar $toj/lib/
cd $toj || exit
echo "One-Jar-Main-Class: cda.App" >> boot-manifest.mf
rm -rf META-INF2 &> /dev/null
mv META-INF META-INF2

cp main/main.jar .

yes | unzip main.jar
rm META-INF -rf
mv META-INF2 META-INF
jar cvfm ../one-jar.jar boot-manifest.mf .
cd ..
# rm -r $toj
